name: zonne
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  smooth_page_indicator: ^1.2.0
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  intl_phone_number_input: ^0.7.4
  dotted_border: ^2.1.0
  flutter_card_swiper: ^7.0.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic


