// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbz87tG4Cjgrv9irHshRcNxS4eOByrRF4',
    appId: '1:548039555527:web:b28d0cb02a8d43589381e2',
    messagingSenderId: '548039555527',
    projectId: 'zonneapp-c9000',
    authDomain: 'zonneapp-c9000.firebaseapp.com',
    storageBucket: 'zonneapp-c9000.appspot.com',
    measurementId: 'G-YSB1WGECPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0WCorLlgHfGSsNz6OPlBPjnKTGaZRLd4',
    appId: '1:548039555527:android:b0a0a4247f26f7079381e2',
    messagingSenderId: '548039555527',
    projectId: 'zonneapp-c9000',
    storageBucket: 'zonneapp-c9000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjZAIGiAGyXAACTguXy9d7-HDQjZMgtQQ',
    appId: '1:548039555527:ios:8dcad67237c132499381e2',
    messagingSenderId: '548039555527',
    projectId: 'zonneapp-c9000',
    storageBucket: 'zonneapp-c9000.appspot.com',
    iosBundleId: 'com.example.zonne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjZAIGiAGyXAACTguXy9d7-HDQjZMgtQQ',
    appId: '1:548039555527:ios:8dcad67237c132499381e2',
    messagingSenderId: '548039555527',
    projectId: 'zonneapp-c9000',
    storageBucket: 'zonneapp-c9000.appspot.com',
    iosBundleId: 'com.example.zonne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbz87tG4Cjgrv9irHshRcNxS4eOByrRF4',
    appId: '1:548039555527:web:516304cb4cef9a1c9381e2',
    messagingSenderId: '548039555527',
    projectId: 'zonneapp-c9000',
    authDomain: 'zonneapp-c9000.firebaseapp.com',
    storageBucket: 'zonneapp-c9000.appspot.com',
    measurementId: 'G-M559F3T2EW',
  );
}
